apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespaces
  - ../../base/traefik
  - ../../base/plantuml
  - ../../base/mqtt
  - ../../base/postgres-shared
  - ../../base/wikijs
  - ../../base/gitea
  - ../../routing/minidev-attached
  - secrets/apps-postgres-secret.yaml
  - secrets/wikijs-secret.yaml
  - secrets/gitea-secret.yaml
