---
- name: Validate mqtt configuration
  ansible.builtin.include_tasks: validate.yml
  when: mqtt_enabled | bool

- name: Install and configure mqtt
  ansible.builtin.include_tasks: install.yml
  when: mqtt_enabled | bool

- name: Verify mqtt
  ansible.builtin.include_tasks: verify.yml
  when: mqtt_enabled | bool
