apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: minidev-platform
    app.kubernetes.io/component: routing
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ grafana_hostname }}`)
      kind: Rule
      middlewares:
        - name: default-security-headers
          namespace: traefik
      services:
        - name: vmks-grafana
          port: 80
  tls:
    certResolver: { { traefik_acme_resolver_name } }
