apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - plantuml-ingressroute.yaml
  - wikijs-ingressroute.yaml
  - gitea-ingressroute.yaml
  - gitea-ssh-ingressroutetcp.yaml
  - openwebrx-ingressroute.yaml
  - nodered-ingressroute.yaml
