FROM jekyll/jekyll:4

USER root

RUN apk add --no-cache ca-certificates build-base git && update-ca-certificates

WORKDIR /srv/jekyll

COPY Gemfile Gemfile.lock* ./
RUN bundle config set path /usr/local/bundle && bundle install

COPY . .

USER jekyll

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0", "--port", "4000", "--source", ".", "--destination", "_site"]