# Placeholder only.
# This file is overwritten during Ansible staging by roles/k8s_apply.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apps
type: Opaque
stringData:
  POSTGRES_DB: wikijs
  POSTGRES_USER: wikijs
  POSTGRES_PASSWORD: "__RENDERED_BY_ANSIBLE__"
