apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: apps
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: minidev-platform
    app.kubernetes.io/component: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea
        app.kubernetes.io/part-of: minidev-platform
        app.kubernetes.io/component: application
    spec:
      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.25.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 22
          envFrom:
            - secretRef:
                name: gitea-secret
          volumeMounts:
            - name: gitea-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
