---
- name: Render Jekyll namespace manifest
  ansible.builtin.template:
    src: namespace.yaml.j2
    dest: /tmp/{{ jekyll_app_name }}-namespace.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Jekyll namespace manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ jekyll_app_name }}-namespace.yaml
  changed_when: false

- name: Render Jekyll deployment manifest
  ansible.builtin.template:
    src: deployment.yaml.j2
    dest: /tmp/{{ jekyll_app_name }}-deployment.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Jekyll deployment manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ jekyll_app_name }}-deployment.yaml
  changed_when: false

- name: Render Jekyll service manifest
  ansible.builtin.template:
    src: service.yaml.j2
    dest: /tmp/{{ jekyll_app_name }}-service.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Jekyll service manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ jekyll_app_name }}-service.yaml
  changed_when: false

- name: Render Jekyll ingressroute manifest
  ansible.builtin.template:
    src: ingressroute.yaml.j2
    dest: /tmp/{{ jekyll_app_name }}-ingressroute.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Jekyll ingressroute manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ jekyll_app_name }}-ingressroute.yaml
  changed_when: false
