---
- name: Assert Jekyll namespace is defined
  ansible.builtin.assert:
    that:
      - jekyll_namespace | length > 0
    fail_msg: "jekyll_namespace must be defined"

- name: Assert Jekyll hostname is defined
  ansible.builtin.assert:
    that:
      - jekyll_hostname | length > 0
    fail_msg: "jekyll_hostname must be defined"

- name: Assert Jekyll image is defined
  ansible.builtin.assert:
    that:
      - jekyll_image | length > 0
    fail_msg: "jekyll_image must be defined"
