---
- name: Wait for any old Jekyll pods to clear
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} get pods -l app={{ jekyll_app_name }}
  register: jekyll_pod_list
  changed_when: false

- name: Wait for Jekyll pod to become Ready
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} wait --for=condition=Ready pod -l app={{ jekyll_app_name }} --timeout=300s
  changed_when: false

- name: Get Jekyll objects
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} get deploy,pods,svc
  register: jekyll_objects
  changed_when: false

- name: Get Jekyll ingressroute
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} get ingressroute {{ jekyll_app_name }} -o yaml
  register: jekyll_ingress
  changed_when: false

- name: Get Jekyll pod logs
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} logs deploy/{{ jekyll_app_name }} -c jekyll --tail=200
  register: jekyll_logs
  changed_when: false
  failed_when: false
