---
- name: Wait for Jekyll deployment rollout
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} rollout status deploy/{{ jekyll_app_name }} --timeout=300s
  changed_when: false

- name: Get Jekyll objects
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} get deploy,pods,svc,pvc
  register: jekyll_objects
  changed_when: false

- name: Get Jekyll ingressroute
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} get ingressroute {{ jekyll_app_name }} -o yaml
  register: jekyll_ingress
  changed_when: false

- name: Get Jekyll pod logs
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl -n {{ jekyll_namespace }} logs deploy/{{ jekyll_app_name }} --tail=200
  register: jekyll_logs
  changed_when: false
  failed_when: false
