# Placeholder only.
# This file is overwritten during Ansible staging by roles/k8s_apply.
apiVersion: v1
kind: Secret
metadata:
  name: wikijs-secret
  namespace: apps
type: Opaque
stringData:
  DB_TYPE: postgres
  DB_HOST: wikijs-postgres
  DB_PORT: "5432"
  DB_NAME: wikijs
  DB_USER: wikijs
  DB_PASS: "__RENDERED_BY_ANSIBLE__"
