---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: yes

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Install required base packages
  ansible.builtin.package:
    name:
      - curl
      - rsync
      - tar
    state: present

- name: Install Helm
  ansible.builtin.shell: |
    set -euo pipefail
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash
    creates: /usr/local/bin/helm
