---
- name: Render PlantUML namespace manifest
  ansible.builtin.template:
    src: namespace.yaml.j2
    dest: /tmp/{{ plantuml_app_name }}-namespace.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply PlantUML namespace manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ plantuml_app_name }}-namespace.yaml
  changed_when: false

- name: Render PlantUML PVC manifest
  ansible.builtin.template:
    src: pvc.yaml.j2
    dest: /tmp/{{ plantuml_app_name }}-pvc.yaml
    owner: root
    group: root
    mode: "0644"
  when: plantuml_persistence_enabled | bool

- name: Apply PlantUML PVC manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ plantuml_app_name }}-pvc.yaml
  changed_when: false
  when: plantuml_persistence_enabled | bool

- name: Render PlantUML deployment manifest
  ansible.builtin.template:
    src: deployment.yaml.j2
    dest: /tmp/{{ plantuml_app_name }}-deployment.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply PlantUML deployment manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ plantuml_app_name }}-deployment.yaml
  changed_when: false

- name: Render PlantUML service manifest
  ansible.builtin.template:
    src: service.yaml.j2
    dest: /tmp/{{ plantuml_app_name }}-service.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply PlantUML service manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ plantuml_app_name }}-service.yaml
  changed_when: false

- name: Render PlantUML IngressRoute manifest
  ansible.builtin.template:
    src: ingressroute.yaml.j2
    dest: /tmp/{{ plantuml_app_name }}-ingressroute.yaml
    owner: root
    group: root
    mode: "0644"
  when: plantuml_ingress_enabled | bool

- name: Apply PlantUML IngressRoute manifest
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s kubectl apply -f /tmp/{{ plantuml_app_name }}-ingressroute.yaml
  changed_when: false
  when: plantuml_ingress_enabled | bool
