apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebrx-data
  namespace: apps
  labels:
    app.kubernetes.io/name: openwebrx
    app.kubernetes.io/part-of: minidev-platform
    app.kubernetes.io/component: storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
