---
- name: Host foundation
  hosts: gitea_hosts
  become: true
  tasks:
    - name: Include host foundation roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ host_foundation_roles | default([]) }}"
